# Generated by Django 5.2.5 on 2025-11-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(choices=[('OES', 'OES'), ('OTC', 'OTC'), ('TSE', 'TSE')], max_length=10)),
                ('code', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('unit', models.IntegerField()),
                ('limit_up', models.FloatField()),
                ('limit_down', models.FloatField()),
                ('reference', models.FloatField()),
                ('update_date', models.CharField(max_length=20)),
                ('margin_trading_balance', models.IntegerField()),
                ('short_selling_balance', models.IntegerField()),
                ('day_trade', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('OnlyBuy', 'Only Buy')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contract',
            },
        ),
    ]
