# Generated by Django 5.2.5 on 2025-11-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=4, max_digits=20)),
                ('underlying_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('bid_side_total_vol', models.IntegerField()),
                ('ask_side_total_vol', models.IntegerField()),
                ('avg_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('close', models.DecimalField(decimal_places=4, max_digits=20)),
                ('high', models.DecimalField(decimal_places=4, max_digits=20)),
                ('low', models.DecimalField(decimal_places=4, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('total_amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('volume', models.IntegerField()),
                ('total_volume', models.IntegerField()),
                ('tick_type', models.IntegerField()),
                ('chg_type', models.IntegerField()),
                ('price_chg', models.DecimalField(decimal_places=4, max_digits=20)),
                ('pct_chg', models.DecimalField(decimal_places=4, max_digits=20)),
                ('simtrade', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contract',
            },
        ),
    ]
