# Generated by Django 5.2.5 on 2025-11-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='amount',
            field=models.DecimalField(decimal_places=4, help_text='成交額 (NTD)', max_digits=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='ask_side_total_vol',
            field=models.IntegerField(help_text='賣盤成交總量 (lot)'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='avg_price',
            field=models.DecimalField(decimal_places=4, help_text='均價', max_digits=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='bid_side_total_vol',
            field=models.IntegerField(help_text='買盤成交總量 (lot)'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='chg_type',
            field=models.IntegerField(help_text='漲跌註記 {1: 漲停, 2: 漲, 3: 平盤, 4: 跌, 5: 跌停}'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='close',
            field=models.DecimalField(decimal_places=4, help_text='成交價', max_digits=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='code',
            field=models.CharField(help_text='商品代碼', max_length=50),
        ),
        migrations.AlterField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='建立時間'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='datetime',
            field=models.DateTimeField(help_text='日期'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='high',
            field=models.DecimalField(decimal_places=4, help_text='最高價(自開盤)', max_digits=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='low',
            field=models.DecimalField(decimal_places=4, help_text='最低價(自開盤)', max_digits=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='open',
            field=models.DecimalField(decimal_places=4, help_text='開盤價', max_digits=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='pct_chg',
            field=models.DecimalField(decimal_places=4, help_text='漲跌幅 (%)', max_digits=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='price_chg',
            field=models.DecimalField(decimal_places=4, help_text='漲跌', max_digits=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='simtrade',
            field=models.IntegerField(help_text='試撮'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='tick_type',
            field=models.IntegerField(help_text='內外盤別 {1: 外盤, 2: 內盤, 0: 無法判定}'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='total_amount',
            field=models.DecimalField(decimal_places=4, help_text='總成交額 (NTD)', max_digits=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='total_volume',
            field=models.IntegerField(help_text='總成交量 (lot)'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='underlying_price',
            field=models.DecimalField(decimal_places=4, help_text='標的物價格', max_digits=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='更新時間'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='volume',
            field=models.IntegerField(help_text='成交量 (lot)'),
        ),
    ]
