# Generated by Django 5.2.6 on 2025-11-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futures', '0002_alter_contract_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='商品代碼', max_length=50)),
                ('datetime', models.DateTimeField(db_index=True, help_text='日期')),
                ('open', models.DecimalField(decimal_places=4, help_text='開盤價', max_digits=20)),
                ('underlying_price', models.DecimalField(decimal_places=4, help_text='標的物價格', max_digits=20)),
                ('bid_side_total_vol', models.IntegerField(help_text='買盤成交總量 (lot)')),
                ('ask_side_total_vol', models.IntegerField(help_text='賣盤成交總量 (lot)')),
                ('avg_price', models.DecimalField(decimal_places=4, help_text='均價', max_digits=20)),
                ('close', models.DecimalField(decimal_places=4, help_text='成交價', max_digits=20)),
                ('high', models.DecimalField(decimal_places=4, help_text='最高價(自開盤)', max_digits=20)),
                ('low', models.DecimalField(decimal_places=4, help_text='最低價(自開盤)', max_digits=20)),
                ('amount', models.DecimalField(decimal_places=4, help_text='成交額 (NTD)', max_digits=20)),
                ('total_amount', models.DecimalField(decimal_places=4, help_text='總成交額 (NTD)', max_digits=20)),
                ('volume', models.IntegerField(help_text='成交量 (lot)')),
                ('total_volume', models.IntegerField(help_text='總成交量 (lot)')),
                ('tick_type', models.IntegerField(help_text='內外盤別 {1: 外盤, 2: 內盤, 0: 無法判定}')),
                ('chg_type', models.IntegerField(help_text='漲跌註記 {1: 漲停, 2: 漲, 3: 平盤, 4: 跌, 5: 跌停}')),
                ('price_chg', models.DecimalField(decimal_places=4, help_text='漲跌', max_digits=20)),
                ('pct_chg', models.DecimalField(decimal_places=4, help_text='漲跌幅 (%)', max_digits=20)),
                ('simtrade', models.IntegerField(help_text='試撮')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='建立時間')),
            ],
            options={
                'db_table': 'k_contract',
                'ordering': ['-datetime'],
                'indexes': [models.Index(fields=['code', '-datetime'], name='k_contract_code_1b635d_idx')],
                'unique_together': {('code', 'datetime')},
            },
        ),
    ]
