# Generated by Django 5.2.6 on 2025-11-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futures', '0003_kcontract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='exchange',
            field=models.CharField(default='TAIFEX', help_text='交易所', max_length=20),
        ),
        migrations.AddField(
            model_name='kcontract',
            name='exchange',
            field=models.CharField(default='TAIFEX', help_text='交易所', max_length=20),
        ),
    ]
