# Generated by Django 5.2.6 on 2025-11-24 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futures', '0004_contract_exchange_kcontract_exchange'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['code'], name='contract_code_995ee9_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['-updated_at'], name='contract_updated_53229f_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['code', '-updated_at'], name='contract_code_99de43_idx'),
        ),
        migrations.AddIndex(
            model_name='kcontract',
            index=models.Index(fields=['-datetime'], name='k_contract_datetim_c7a3fb_idx'),
        ),
        migrations.AddIndex(
            model_name='kcontract',
            index=models.Index(fields=['code'], name='k_contract_code_8cf108_idx'),
        ),
    ]
