# Generated by Django 5.2.6 on 2025-11-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futures', '0005_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='是否為活躍契約（正在交易中）'),
        ),
    ]
