# Generated by Django 5.2.6 on 2025-11-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futures', '0006_contract_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='code',
            field=models.CharField(db_index=True, help_text='商品代碼', max_length=50, unique=True),
        ),
    ]
