# Generated by Django 5.2.6 on 2025-11-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futures', '0007_alter_contract_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='code',
            field=models.CharField(db_index=True, help_text='商品代碼', max_length=50),
        ),
    ]
